% File src/library/BitsnBobs/vignettes/wizard.Rnw
% Part of the BitsnBobs package, https://mark-eis.github.io/BitsnBobs/
% Copyright 2024-2026 Mark Eisler
% Distributed under the MIT License

\documentclass[a4paper]{article}

\usepackage{Rd}
\usepackage{hyperref}

\hypersetup{colorlinks = true, linkcolor = blue, urlcolor = blue}

\setlength{\parindent}{0in}
\setlength{\parskip}{.1in}
\setlength{\textwidth}{140mm}
\setlength{\oddsidemargin}{10mm}

\title{Using the wizard function}
\author{Mark Eisler}
% \VignetteIndexEntry{Using the wizard function}
% \VignettePackage{BitsnBobs}

\begin{document}

\maketitle

<<echo=FALSE, results=hide>>=
library(BitsnBobs)
library(rlang)
options(width = 80, continue = "  ",
        try.outFile = stdout())
@

\section{Introduction}

The \code{wizard()} function extracts and sorts unique values of a selected
column from a data frame, and optionally pastes into a character string.

For our examples, we will use the \code{mtcars} data.

\section{Using a symbol argument}

\code{wizard(data, col, .collapse = NULL)} uses a symbol for its
\code{<data-masking>} argument \code{col}.

<<a>>=
mtcars |> wizard(cyl)
@

This shows sorted unique values of the \code{cyl} column of
\code{mtcars}.

If there is a potentially confounding variable of the same name in the
global environment,

<<>>=
(cyl <- c(100:110))
@

...nevertheless, \code{<data-masking>} ensures that the \code{col}
argument of \code{wizard} correctly refers to the \code{cyl} column of the
\code{mtcars} data.

<<>>=
<<a>>
@

But say there's a similar variable \code{Cyl} in the global environment,

<<>>=
Cyl <- "Bad Luck!"
@

...and we confuse \code{cyl}  with \code{Cyl}, we obtain an unexpected
and puzzling result: -

<<>>=
mtcars |> wizard(Cyl)
@

\section{Using the \code{.data} pronoun}

Using the \code{.data} pronoun\textsuperscript{1} from the \strong{rlang} package
circumvents this problem by throwing a meaningful error message: -

<<>>=
mtcars |> wizard(.data$cyl)
try(mtcars |> wizard(.data$Cyl))
@

\section{Symbolise and inject}

The \code{col} argument might be saved as a character variable, for example: -

<<>>=
(col_var <- "cyl")
@

...which needs converting to a symbol and injecting\textsuperscript{1} using
the injection operator \code{!!} from the \strong{rlang} package: -

<<b>>=
mtcars |> wizard(!!sym(col_var))
@

Again, if we confuse \code{cyl}  with \code{Cyl}, we obtain an unexpected
and confusing result: -

<<>>=
(col_var <- "Cyl")
<<b>>
@

Using \code{data\_sym()} from \strong{rlang} prevents this problem by prefacing
the symbol with the data pronoun: -

<<>>=
data_sym(col_var)
try(mtcars |> wizard(!!data_sym(col_var)))
@

\section{Examples using \code{lapply()}}

(We could also use \code{purrr::map()}, but it has no particular advantage
here so \strong{base} \code{lapply()} is preferable.)

<<>>=
mtcars |> lapply(wizard, data = mtcars)
@

Here we use \code{setNames()} to obtain an eponymously named character vector
of the first four \code{mtcar} names: -

<<>>=
(carnames <- setNames(nm = names(mtcars))[1:4])
@

...and use it in three equivalent versions where \code{lapply()} uses the
\code{.data} pronoun, \code{data\_sym()} or \code{data\_syms()} in an
anonymous function: -

<<>>=
carnames |> lapply(\(x) wizard(mtcars, .data[[x]]))
carnames |> lapply(\(x) wizard(mtcars, !!data_sym(x)))
carnames |> data_syms() |> lapply(\(x) wizard(mtcars, !!x))
@

If one of the names is incorrect: - 

<<>>=
carnames["cyl"] <- "Cyl"
carnames
@

...these all provide meaningful error messages as previously shown: - 

<<>>=
try(carnames |> lapply(\(x) wizard(mtcars, .data[[x]])))
try(carnames |> lapply(\(x) wizard(mtcars, !!data_sym(x))))
try(carnames |> data_syms() |> lapply(\(x) wizard(mtcars, !!x)))
@

Without the \code{.data} pronoun, the error might be overlooked: -

<<>>=
carnames |> lapply(\(x) wizard(mtcars, !!sym(x)))
carnames |> syms() |> lapply(\(x) wizard(mtcars, !!x))
@

\section{References}

1. \href{https://rlang.r-lib.org/reference/dot-data.html}{\strong{rlang} \code{.data} and \code{.env} pronouns}

2. \href{https://rlang.r-lib.org/reference/topic-metaprogramming.html#symbolise-and-inject}{\strong{rlang} symbolise and inject}

\end{document}
